### PR TITLE
Add entropic line constraint

### PR DESCRIPTION
**Pull request by mossx-dev**
Entropic lines are defined with the following rules:

- Any set of three sequential cells along an entropic line must contain a low digit (1-3), a middle digit (4-6), and a high higit (7-9)
- Digits my repeat on a line, if allowed by other rules.
- An entropic line of length two may not contain two digits from the same rank.

Currently the entropic lines are part of the new constraints javascript file. The true candidates and brute force solving are implemented and have had basic testing done. Logic solve steps have not been tested.

### CODE REVIEW

**Review by dclamage — CHANGES_REQUESTED** [review]
It appears some kind of auto-formatting happened for the newconstraints javascript file which doesn't match my own auto-formatting. Is it possible that the changes can be limited to just what you added, rather than having all these whitespace changes?

Otherwise, the code looks good, ty :)

**Comment by mossx-dev** [comment]
Sorry about that, had some issues with VSCode. Just committed a change that should fix it. Hope everything looks good!

**Comment by dclamage** [comment]
Hi @mossx-dev - please see Issue #96 . Are you able to fix this?

**Comment by mossx-dev** [comment]
Just made a pull request #97 which fixed that issue for me. Hope everything looks good, I made sure there were no issues with auto-formatting this time :).

**Pull request merged**
